{
 "title": "Dubbo Application Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application_name",
    "label": "application_name",
    "query": {
     "query": "label_values(dubbo_application_info_total{}, application_name)"
    }
   },
   {
    "name": "application_version",
    "label": "application_version",
    "query": {
     "query": "label_values(dubbo_application_info_total{application_name=\"$application_name\"}, application_version) "
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dubbo_application_info_total{application_name=\"$application_name\",application_version=\"$application_version\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "application_name",
   "type": "text",
   "description": "application_info",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;font-size:30px\">${application_name}：${application_version}\n \n</div>\n\n \n"
   },
   "targets": [
    {
     "expr": "qps{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "provider_success_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_succeed_total{instance=\"$instance\"})   / sum(dubbo_provider_requests_total{instance=\"$instance\"})  ) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_network_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_failed_network_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_business_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_business_failed_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_limit_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_limit_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_unknown_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_unknown_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_request_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_failed_total{instance=\"$instance\"})  / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_failed_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_processing_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_processing{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_timeout_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_timeout_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_service_unavailable_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_failed_service_unavailable_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_service_unavailable_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_failed_service_unavailable_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "provider_codec_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_provider_requests_failed_codec_total{instance=\"$instance\"}) / sum(dubbo_provider_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Provider Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "provider_qps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dubbo_provider_qps_total{instance=\"$instance\"} OR on() vector(0) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_total(2m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_requests_total{instance=\"$instance\"}[2m]) OR on() vector(0) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_processing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_processing{instance=\"$instance\"} OR on() vector(0) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_succeed(2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_requests_succeed_total{instance=\"$instance\"}[2m]) OR on() vector(0) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_total_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_total_aggregate{instance=\"$instance\"} OR on() vector(0) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_succeed_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_succeed_aggregate{instance=\"$instance\"} OR on() vector(0) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Provider RT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "provider_rt_sum(2m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_rt_milliseconds_sum{instance=\"$instance\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_avg ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "increase(dubbo_provider_rt_milliseconds_sum{instance=\"$instance\"}[2m]) / increase(dubbo_provider_requests_total{instance=\"$instance\"}[2m]) ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_milliseconds_min{instance=\"$instance\"}   ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_milliseconds_max{instance=\"$instance\"} ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_last",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_milliseconds_last{instance=\"$instance\"}  ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": " provider_rt_p95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_milliseconds_p95{instance=\"$instance\"} OR vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_rt_p99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_milliseconds_p99{instance=\"$instance\"} ",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "dubbo_provider_rt_seconds_histogram",
     "type": "heatmap",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "dubbo_provider_rt_seconds_histogram_seconds_bucket{instance=\"$instance\"}",
       "legendFormat": "{{application_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Provider Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "provider_requests_failed_total[2m]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "increase(dubbo_provider_requests_failed_total{instance=\"$instance\"}[2m]) OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_limit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_limit_total{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_business_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_business_failed_total{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_unknown_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_unknown_failed_total{instance=\"$instance\"}OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "provider_requests_timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "dubbo_provider_requests_timeout_total{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "consumer_success_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_succeed_total{instance=\"$instance\"})   / sum(dubbo_consumer_requests_total{instance=\"$instance\"})  ) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_network_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_failed_network_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_business_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_business_failed_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_limit_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_limit_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_unknown_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_unknown_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_request_failed_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_failed_total{instance=\"$instance\"})  / sum(dubbo_cconsumer_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_error_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_failed_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_processing_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_processing{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_timeout_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_timeout_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_service_unavailable_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_failed_service_unavailable_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_service_unavailable_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_failed_service_unavailable_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "consumer_codec_rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(dubbo_consumer_requests_failed_codec_total{instance=\"$instance\"}) / sum(dubbo_consumer_requests_total{instance=\"$instance\"})) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "consumer_qps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "dubbo_consumer_qps_total{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_request_total(2m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_requests_total{instance=\"$instance\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "increase_consumer_requests_processing[2m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_processing{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_succeed(2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_requests_succeed_total{instance=\"$instance\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_total_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_total_aggregate{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_succeed_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_succeed_aggregate{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer RT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "consumer_rt_sum(2m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_rt_milliseconds_sum{instance=\"$instance\"}[2m])",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_min{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_all_rt_max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_max{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_avg ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_avg{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_last",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_last{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_p95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_p95{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_rt_p99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_p99{instance=\"$instance\"}",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "consumer_requests_failed_total[2m]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_requests_failed_total{instance=\"$instance\"}[2m]) OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_limit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_limit_total{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_business_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_business_failed_total{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_unknown_failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_unknown_failed_total{instance=\"$instance\"}OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_timeout_total{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_failed_network_total_aggregate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "dubbo_consumer_requests_failed_network_total_aggregate{instance=\"$instance\"} OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "consumer_requests_failed_network_total[2m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "increase(dubbo_consumer_requests_failed_network_total{instance=\"$instance\"}[2m]) OR on() vector(0)",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "register_instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "dubbo_registry_register_requests_total{instance=\"$instance\"}",
       "legendFormat": "register_instance_total_num"
      },
      {
       "expr": "(dubbo_registry_register_requests_succeed_total{instance=\"$instance\"})",
       "legendFormat": "register_succeed_total"
      },
      {
       "expr": "(dubbo_registry_register_requests_failed_total{instance=\"$instance\"})  OR on() vector(0)",
       "legendFormat": "register_requests_failed_total"
      }
     ]
    },
    {
     "title": "register_instance_rt",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "dubbo_register_rt_milliseconds_sum{instance=\"$instance\"}",
       "legendFormat": "register_rt_milliseconds_sum"
      },
      {
       "expr": "(dubbo_register_rt_milliseconds_avg{instance=\"$instance\"})",
       "legendFormat": "register_rt_milliseconds_avg"
      },
      {
       "expr": "(dubbo_register_rt_milliseconds_max{instance=\"$instance\"})",
       "legendFormat": "register_rt_milliseconds_max"
      },
      {
       "expr": "(dubbo_register_rt_milliseconds_min{instance=\"$instance\"})",
       "legendFormat": "register_rt_milliseconds_min"
      },
      {
       "expr": "(dubbo_register_rt_milliseconds_last{instance=\"$instance\"})",
       "legendFormat": "register_rt_milliseconds_last"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "provider_metadata",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "dubbo_metadata_push_num_total{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "metadata_push_num_total"
      },
      {
       "expr": "dubbo_metadata_push_num_succeed_total{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "metadata_push_num_succeed_total"
      },
      {
       "expr": "dubbo_metadata_push_num_failed_total{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "metadata_push_num_failed_total"
      }
     ]
    },
    {
     "title": "provider_metadata_rt",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "dubbo_push_rt_milliseconds_sum{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "push_rt_milliseconds_sum"
      },
      {
       "expr": "dubbo_push_rt_milliseconds_last{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "push_rt_milliseconds_last"
      },
      {
       "expr": "dubbo_push_rt_milliseconds_min{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "push_rt_milliseconds_min"
      },
      {
       "expr": "dubbo_push_rt_milliseconds_max{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "push_rt_milliseconds_max "
      },
      {
       "expr": "dubbo_push_rt_milliseconds_avg{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "push_rt_milliseconds_avg "
      }
     ]
    },
    {
     "title": "consumer_metadata",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "dubbo_metadata_subscribe_num_total{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "metadata_subscribe_num_total"
      },
      {
       "expr": "dubbo_metadata_subscribe_num_succeed_total{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "metadata_subscribe_num_succeed_total"
      },
      {
       "expr": "dubbo_metadata_subscribe_num_failed_total{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "metadata_subscribe_num_failed_total"
      }
     ]
    },
    {
     "title": "consumer_metadata_rt",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "dubbo_subscribe_rt_milliseconds_sum{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "subscribe_rt_milliseconds_sum"
      },
      {
       "expr": "dubbo_subscribe_rt_milliseconds_last{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "subscribe_rt_milliseconds_last"
      },
      {
       "expr": "dubbo_subscribe_rt_milliseconds_min{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "subscribe_rt_milliseconds_min"
      },
      {
       "expr": "dubbo_subscribe_rt_milliseconds_max{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "subscribe_rt_milliseconds_max "
      },
      {
       "expr": "dubbo_subscribe_rt_milliseconds_avg{instance=\"$instance\"}  OR on() vector(0)",
       "legendFormat": "subscribe_rt_milliseconds_avg "
      }
     ]
    }
   ]
  },
  {
   "title": "ConfigCenter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread_Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "dubbo_thread_pool_core_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_core_size{instance=\"$instance\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "dubbo_thread_pool_active_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_active_size{instance=\"$instance\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "dubbo_thread_pool_thread_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_thread_count{instance=\"$instance\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "dubbo_thread_pool_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_queue_size{instance=\"$instance\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "dubbo_thread_pool_max_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_max_size{instance=\"$instance\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "dubbo_thread_pool_largest_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_largest_size{instance=\"$instance\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    }
   ]
  }
 ]
}